@startuml
 !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

 title C4 Context Diagram for Heating Home Monolith

 Person(user, "User", "User of the smart home")
 System_Ext(sensor, "Sensor", "Temperature sensor in home")

 System(HeatingHomeMonolith, "Heating Home Monolith", "Fetches data from devices and monitors temperature in smart home")
 

 Rel(user, HeatingHomeMonolith, "Uses")
 Rel(HeatingHomeMonolith, sensor, "Fetches data")
@enduml