@startuml
entity "User" as user {
    * id : Long
    --
    name : String
    email : String
    password : String
}

entity "House" as house {
    * id : Long
    --
    user_id : Long
    address : String
}

entity "Device" as device {
    * id : Long
    --
    type_id : Long
    house_id : Long
    serial_number : String
    status : String
}

entity "DeviceType" as deviceType {
    * id : Long
    --
    name : String
}

entity "TelemetryData" as telemetryData {
    * id : Long
    --
    device_id : Long
    timestamp : Date
    data : JsonString
}


entity "ScenarioSchedule" as scenarioSchedule {
    * id : Long
    --
    house_id : Long
    scenario_plan : JsonString
    cron: Stgring
}

entity "ScenarioScheduleDevice" as scenarioScheduleDevice {
    * scenario_id : Long
    * device_id : Long
    --
}

user ||--o{ house : "owns"
house ||--o{ device : "contains"
device ||--o| deviceType : "has"
device ||--o{ telemetryData : "generates"
device ||--o| scenarioScheduleDevice : "has"
scenarioSchedule ||--o| scenarioScheduleDevice : "has"
house ||--o{ scenarioSchedule : "owns"
@enduml